In [6]:
import numpy as np

## Problem 1:

x_vals = np.array([-1.6])
for j in range(1000):
    x_j = x_vals[j] - (x_vals[j] * np.sin(3 * x_vals[j]) - np.exp(x_vals [j]))/(np.sin(3 * x_vals [j]) + 3 * x_vals[j]* np.cos(3 * x_vals [j]) - np.exp(x_vals[j]))
    x_vals = np.append(x_vals ,x_j)
    
    f_x = x_vals[j] * np.sin(3 * x_vals [j]) - np.exp(x_vals [j])
    
    if abs(f_x) < 1e-6:
        break
    
#print(x_vals)
#print(j)

A1 = x_vals

#print(len(x_vals)-1)

## Problem 1 part 2:
a = -0.7
b = -0.4

mid = []

for j in range(0, 1000):
    c = (a + b)/2
   
    mid.append(c)
   
    fc = c * np.sin(3 * c) - np.exp(c)
    
    #print(c)

    if abs(fc) < 1e-6 :
        break
    
    if ( fc > 0 ):
        a = c
    else:
        b = c
        
 
#print(mid)
#print(fc)

iterations = j + 1
#print(iterations)
A2 = mid

A3 = np.array([len(x_vals) - 1, iterations])

print(A1)
print(A2)
print(A3)

## Problem 2

A = np.array([[1,2],[-1,1]])
B = np.array([[2,0],[0,2]])
C = np.array([[2,0,-3],[0,0,-1]])
D = np.array([[1,2],[2,3],[-1,0]])
x = np.array([1,0])
y = np.array([0,1])
z = np.array([1,2,-1])

A4 = A + B
A5 = 3 * x - 4 * y
A6 = np.dot(A, x) 
A7 = np.dot(B, x - y) 
A8 = np.dot(D, x) 
A9 = np.dot(D, y) + z
A10 = np.dot(A, B) 
A11 = np.dot(B, C) 
A12 = np.dot(C, D) 

print(A4)
print(A5)
print(A6)
print(A7)
print(A8)
print(A9)
print(A10)
print(A11)
print(A12)

[-1.6         3.19799514  2.46440244  1.2035359   0.65020146 -0.11692334
 -0.66052349 -0.52192654 -0.56655274 -0.57074658 -0.57078962 -0.57078962]
[-0.55, -0.625, -0.5875, -0.5687500000000001, -0.578125, -0.5734375, -0.5710937500000001, -0.5699218750000001, -0.5705078125, -0.57080078125, -0.570654296875, -0.5707275390625, -0.57076416015625, -0.570782470703125, -0.5707916259765625, -0.5707870483398438, -0.5707893371582031]
[11 17]
[[ 3  2]
 [-1  3]]
[ 3 -4]
[ 1 -1]
[ 2 -2]
[ 1  2 -1]
[ 3  5 -1]
[[ 2  4]
 [-2  2]]
[[ 4  0 -6]
 [ 0  0 -2]]
[[5 4]
 [1 0]]
